In [1]:
from sklearn.datasets import load_boston

boston = load_boston()

dfX = pd.DataFrame(boston.data, columns=boston.feature_names)
dfy = pd.DataFrame(boston.target, columns=["MEDV"])
df = pd.concat([dfX, dfy], axis=1)

model1 = sm.OLS.from_formula("MEDV ~ " + "+".join(boston.feature_names), data=df)
result1 = model1.fit()
print(result1.summary())

                            OLS Regression Results                            
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Thu, 14 May 2020   Prob (F-statistic):          6.72e-135
Time:                        10:11:58   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     36.4595      5.103      7.144      0.0

[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

- 조건수(conditiona number)가 15100으로 너무 큽니다. 
강한 다중공선성(multicollinearity)이나 다른 수치적 문제가 있을 수 있습니다.

#### 조건수에 따른 해의 값 변화
- Ax = b
- A : 공분산 행렬, x : 해, b : 상수 벡터

In [2]:
# A가 조건수가 1인 단위벡터인 경우
A = np.eye(4)

In [3]:
# 오차가 없는 경우의 해
b = np.ones(4)
x = sp.linalg.solve(A, b)
x

array([1., 1., 1., 1.])

In [4]:
# 행렬 A에 1/10000 오차가 생기면 x도 유사한 정도의 오차 발생
x_error = sp.linalg.solve(A + 0.0001 * np.eye(4), b)
x_error

array([0.99990001, 0.99990001, 0.99990001, 0.99990001])

In [5]:
#  조건수가 15513인 4차 힐버트 행렬 A
A = sp.linalg.hilbert(4)
np.linalg.cond(A)

15513.738738929038

In [6]:
# 오차가 없는 경우의 x의 해
sp.linalg.solve(A, b)

array([  -4.,   60., -180.,  140.])

In [ ]:
# 행렬 A에 1/10000 오차가 발생한 경우
sp.linalg.s