### 1. 기초문법(Python Basic Syntax)

#### 1-1. 식별자
- 식별자 규칙
    - 소문자, 대문자, 숫자, (_) 사용
    - 가장 앞에 숫자 사용 불가능
    - 예약어 사용 불가
    - 컨벤션
        - snake case : fast_campus - 변수명, 함수명에 사용
        - camel case : FastCampus,fastCampus - 클래스명에 사용

#### 1-2. 데이터 타입
- 기본 데이터 타입 : int, float, bool, str
- 컬렉션 데이터 타입 : list, tuple, dict

In [2]:
# 문자열 데이터 타입의 함수
# 대문자변환(upper), 소문자변환(lower), 공백제거(strip), 문자열 치환(replace)
upper_a = 'abc'
lower_b = 'ABC'
strip_c = '   Fast'

upper_a.upper(), lower_b.lower(), strip_c.strip(), strip_c.replace("Fast", "Slow")

('ABC', 'abc', 'Fast', '   Slow')

#### 1-3. 오프셋 인덱스

In [5]:
g = 'abcdefgh'
g[2], g[-2], g[2:5], g[3:], g[-2:], g[::2][::-1]

('c', 'g', 'cde', 'defgh', 'gh', 'geca')

#### 1-4. list - 수정 가능 데이터
- 함수
    - append : 가장 뒤에 값을 추가
    - sort : 오름차순 정렬
        - 내림차순 : sort 수행후 reverse
    - reverse : 데이터를 역순으로 정렬
    - pop : 가장 마지막 데이터 출력하고 리스트에서 삭제
    - copy : 리스트 내용 복사

In [12]:
ls = [1, 5, 2, 4]
ls.sort()
print(ls)

[1, 2, 4, 5]


In [13]:
# append
print(ls)
ls.append(3)
ls

[1, 2, 4, 5]


[1, 2, 4, 5, 3]

In [14]:
# sort & reverse
print(ls)
ls.sort()
ls.reverse()
ls

[1, 2, 4, 5, 3]


[5, 4, 3, 2, 1]

In [15]:
# pop
num = ls.pop()
num, ls

(1, [5, 4, 3, 2])

In [16]:
# copy  ls1 = ls2 할 경우 얕은 복사로 값 수정시 ls1, ls2 모두 수정됨
ls1 = [1, 2, 3]
ls2 = ls1.copy()
ls1[2] = 10
ls1, ls2

([1, 2, 10], [1, 2, 3])

#### 1-5. tuple - 수정이 불가능
- 기본적인 선언 및 인덱스 사용방법은 리스트와 동일

#### 1-6. dict
- 순서가 없고 {키:값}으로 구성되어 있는 데이터 타입

In [17]:
# 선언 : 키 - 정수, 문자열 데이터 타입만 가능, 인덱스 대신 키값 사용
dic = {
    1:"one",
    "two":2,
    "three":[1,2,3]
}
dic

{1: 'one', 'two': 2, 'three': [1, 2, 3]}

In [30]:
# dic["키값"] -> 키가 가르키는 value값 출력
# dic["키값"] = value -> 키가 가르키는 value값을 변경
# dic.items() : key 값과 value값으로 이루어진 튜플 생성
print(dic[1])
dic[1] = "일"
print(dic[1])
print(dic.items())

일
일
dict_items([(1, '일'), ('two', 2), ('three', [1, 2, 3])])


#### 1-7. 형변환
- 딕셔너리를 리스트로 바꾸는 법
- 리스트를 딕셔너리 데이터로 바꾸는 법(zip함수)

In [21]:
# 딕셔너리 -> 리스트
# 딕셔너리 이름을 리스트로 변환하면 key값을 리스트로 바꿈
# 딕셔너리 value값을 리스트로 변환하면 value값을 리스트 형태로 바꿈
dic_key = list(dic)
dic_value = list(dic.values())
dic_key, dic_value

([1, 'two', 'three'], ['일', 2, [1, 2, 3]])

In [19]:
# 리스트 -> 딕셔너리
city = ['seoul', 'busan', 'daegu']
population = [970, 340, 248]
dict(zip(city, population))

{'seoul': 970, 'busan': 340, 'daegu': 248}

#### 1-8. 연산자
- 산술 연산자 : `합(+), 차(-), 곱(*), 나누기(/), 몫(//), 나머지(%), 제곱(**)`
- 할당 연산자 : `변수에 누적시켜서 연산 : +=, -=, *=, /= , ....`
- 비교 연산자 : ==, !=, >, <, >=, <= : 결과 True, False
- 논리 연산자 : True와 False를 연산
    - or : 모든 값이 False일 때, False 출력
    - and : 모든 값이 True일 때, True 출력
    - not : True -> False, False -> True
- 멤버 연산자 : 특정 데이터가 있는지 확인할때 사용 : not in, in -> 결과 : True, False

In [23]:
# 멤버 연산
'seoul' in city

True

### 2. 조건문(Condition)
- 조건 부분에 bool 데이터 타입 이외의 데이터 타입이 오면 자동으로 bool으로 형변환
    - int : 0 - False, 나머지 True
    - float : 0.0 - False, 나머지 True
    - list, tuple, dict : [],(),{} - False(값이 없음), 나머지 True

In [25]:
for x in range(5):
    if(x%2):
        print("even")
    else:
        print("odd")

odd
even
odd
even
odd


### 3. 반복문(Loop)

#### 3-1. while
- 무한루프 : 조건을 항상 참인 경우 루프가 무한히 돌아감 ex) 1
- break : 반복문을 중단 시킴

In [27]:
data = [1, 2, 3]
while data :       #조건이 False가 될때까지 구문 실행
    print (data)
    data.pop()     #data 값을 출력 후 삭제

[1, 2, 3]
[1, 2]
[1]


In [49]:
# 6자리의 로또번호를 생성하는 코드를 작성
# 6자리의 번호는 중복 x
import random

lotto = []
while True:
    if len(lotto) < 6 :
         num = random.randint(1,45)
         if num not in lotto :
            lotto.append(num)
    else :
         lotto.sort()
         print (lotto)
         break

[9, 12, 17, 29, 33, 41]


#### 3-2. for
- iterable한 값을 하나씩 꺼내서 value에 대입후 코드를 iterabel 변수의 값 개수만큼 실행
- for문에서 iterable 데이터가 tuple로 나오면 여러개의 변수로 받아짐
````
for <variable> in <iterables>:
    <code>
````
- continue : continue절 아래의 코드는 생략하고 다시 조건부분으로 올라가서 코드 실행
- range 함수
    - range(start, end, split)
        - ex) `range(10) -> 0~9, range(1,100) -> 1~99, range(0,10,2) -> 0,2,4,6,8`

In [28]:
ls = [0, 1, 2, 3, 4]
for data in ls : 
    if data % 2 :       # data가 홀수면 다시 조건부분부터 실행
        continue
    print(data, end=" ")

0 2 4 

In [29]:
for x in range(0,10,2):
    print(x)

0
2
4
6
8


In [31]:
subject_ls = ['Korean', 'English', 'Math']
points_ls =[80, 90, 100]
points_dict = dict(zip(subject_ls,points_ls))

for subject, point in points_dict.items():
    print(subject, point)

Korean 80
English 90
Math 100


In [39]:
# 구구단 출력 가로 출력
# print : end="\t" -> tap만큼 간격
for dan in range(2, 10):
    for cnt in range(2, 10):
        if dan >= cnt:
            print("{} x {} = {}".format(dan, cnt, dan*cnt),end="\t")
    print()

2 x 2 = 4	
3 x 2 = 6	3 x 3 = 9	
4 x 2 = 8	4 x 3 = 12	4 x 4 = 16	
5 x 2 = 10	5 x 3 = 15	5 x 4 = 20	5 x 5 = 25	
6 x 2 = 12	6 x 3 = 18	6 x 4 = 24	6 x 5 = 30	6 x 6 = 36	
7 x 2 = 14	7 x 3 = 21	7 x 4 = 28	7 x 5 = 35	7 x 6 = 42	7 x 7 = 49	
8 x 2 = 16	8 x 3 = 24	8 x 4 = 32	8 x 5 = 40	8 x 6 = 48	8 x 7 = 56	8 x 8 = 64	
9 x 2 = 18	9 x 3 = 27	9 x 4 = 36	9 x 5 = 45	9 x 6 = 54	9 x 7 = 63	9 x 8 = 72	9 x 9 = 81	


#### 3-3. List Comprehention
- 리스트 데이터를 만들어 주는 방법
- for문보다 빠르게 동장
````
[ <conditional> for <valiable> in <iterable> ]
[ data**2 for data(변수) in ls ]
[ ('홀수' if data%2 else '짝수') for data in ls ]
````

In [40]:
# ls에서 뽑은 값을 변환시킬때 -> 조건절에서 data에 함수를 넣어줌
ls = [1, 2, 3, 4, 5]
result = [data**2 for data in ls]
result

[1, 4, 9, 16, 25]

In [41]:
# ls에서 특정 값을 뽑을 때 조건절 사용
ls = range(10)
[data for data in ls if data%2]

[1, 3, 5, 7, 9]

### 4. 함수(Function)

#### 4-1. 함수 선언과 호출
````
# 선언
def function_name (<parameter>):
    <code>
    
# 호출
function_name(<argument>)
````
- parameter : 함수를 선언할때 호출하는 부분에서 보내주는 데이터를 받는 변수
- argument : 함수를 호출할때 함수에 보내주는 데이터

In [45]:
def plus(num1, num2=10):      #parameter : num1, num2 = 10 -> num2의 default값: 10
    print(num1 + num2)

plus(1), plus(1,5), plus(1, num2 = 4) # argument 이름을 명시 -> kwargument

11
6
5


(None, None, None)

#### 4-2. 리턴
- 함수를 실행한 결과를 저장
- return
- return문이 실행되면 그 즉시 함수 실행 종료 -> return문 이하의 코드는 실행되지 않음

In [46]:
def return_test(num1, num2, num3):
    if num1 > num2 :
        return num1
    num = num1 + num2 + num3
    return num

return_test(1, 2, 3), return_test(3, 2, 1)

(6, 3)

#### 4-3. `*args, **kwargs`
- 함수를 호출할때 아규먼트와 키워드 아규먼트의 갯수를 특정지을수 없을때 사용
- `*args`는 튜플 데이터형으로 값 저장
- `**kwargs`는 딕셔너리 데이터형으로 값 저장

In [47]:
def plus(*args, **kwargs):
    print(type(args),args)
    print(type(kwargs), kwargs)
    return sum(args) + sum(list(kwargs.values()))

In [48]:
plus(1,2,3,4,5, num3 =5)

<class 'tuple'> (1, 2, 3, 4, 5)
<class 'dict'> {'num3': 5}


20

#### 4-4. Docstirng
- 함수 설명 작성
````
def echo(msg):
    "한줄의 Docstring 작성"
    """
    여러줄의 Docstring 내용 작성
    """
    <code>
````
- Docstring 보는 법
    - shift + tab
    - (함수명)?
    - (함수명)?? : 소스코드를 볼 수 있음
    - help(함수명) : 함수의 docstring 부분이 출력
    - print(함수명.doc) : 함수의 docstring 부분 출력

#### 4-5. Scope : 범위
- 함수 안에서 선언되는 변수와 함수 밖에서 선언되는 변수의 범위가 다름
- global(전역), local(지역)
- 지역 내에서 전역변수 선언 방법 -> global <변수명>

#### 4-6. Inner Function
- 함수가 지역영역에 선언, 함수 안에 함수가 선언
````
# inner function
    def outer(a,b): 
        def inner(c,d):
            return c + d
        return inner(a, b)
    outer(2, 3)
````
- callback function : 함수를 argument parameter로 설정해서 사용
````
# callback function
    def calc(func, a, b):
        return func(a, b)

    def plus(a, b):
        return a + b
    
    calc(plus, 12, 34)
````

#### 4-7. 람다함수
- parameter를 간단한 계산으로 리턴하는 함수 : 삼항연산과 유사
````
def plus(a, b):
    return a + b
<함수명> = lambda <변수> : <연산식>
````

In [52]:
# 리스트를 사용한 람다함수 활용
ls = range(5)
plus = lambda *args : sum(*args)
plus(ls)

10

#### 4-8. map, filter, reduce
- map : 순서가 있는 데이터 집합에서 모든 값에 함수를 적용시킨 결과를 출력
- filter : 리스트 데이터에서 특정 조건에 맞는 value만 남기는 함수
- reduce : 리스트 데이터를 처음부터 순서대로 특정 함수를 실행하여 결과를 누적시켜주는 함수

In [57]:
# map
ls = range(5)
func = lambda data : 'odd' if data % 2 else 'even'

list(map(func, ls))

['even', 'odd', 'even', 'odd', 'even']

In [59]:
# filter
func = lambda data: True if data %2 else False
list(filter(func, ls))

[1, 3]

In [60]:
# Reduce
from functools import reduce
ls = [3, 1, 2, 4, 5]
reduce(lambda x, y : x + y, ls)

15

#### 4-9. decorator
 - 함수에서 코드를 바꾸지 않고 기능을 추가하거나 수정하고 싶을때 사용하는 문법
 - 데코레이터의 사용
 ```
 def c(func):
     def wraper(*args, **kwargs):
         code_1
         result = func(*args, **kwargs)
         code_3
         return result
     return wraper
     
 @c
 def a():
     code_2
 @c
 def b():
     code_4
 ```

### 5. 클래스(Class)
- 변수와 함수를 모아서 사용하는 문법
- 객체지향을 구현하기 위해 만든 문법
    - 객체지향 : 실제세계를 반영해서 코드를 작성하는 방법
    - 여러명이 개발할때 효율적으로 코드를 작성할수 있도록 하는 개념
- 클래스의 선언 -> 객체생성 -> 객체의 함수 사용

#### 5-1. 클래스 구조
````
class Data:
    
    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2

        
    def disp(self):
        print(self.num1, self.num2)
````

####  5-2. 생성자
- 클래스가 객체로 생성될때 실행되는 함수
- 변수(재료)를 추가할때 사용
````
생성자 함수 : __init__
````

#### 5-3. 상속
- 클래스의 기능을 가져다가 기능을 수적하거나 추가할때 사용하는 방법
````
    class Calculator :
        def __init__(self, num1, num2):
            self.num1 = num1
            self.num2 = num2
        
        def plus(self):
            return self.num1 + self.num2
    
    # 상속을 사용하여 class 함수 추가
    class Calculator2(Calculator):
        def minus(self):
            return self.num1 - self.num2
````
- 메서드 오버라이딩
````
class Calculator4(Calculator2):
    def plus(self):
        return self.num1**2 + self.num2**3
````

#### 5-4. super
- 부모 클래스에서 사용된 함수의 코드를 가져다가 자식 클래스의 함수에서 재사용할때
````
    class A:
        def plus(self):
            code1

    class B(A):
        def minus(self):
            code1      # super().plus()
            code2
````

#### 5-5. getter, setter
- 객체의 변수에 접근할때 함수로 접근하도록하기 위한 문법
````
class Car:
    
    def __init__(self, init_speed = 0):
        self.speed = init_speed
        self.__max_speed = 200
        
    def add_speed(self, speed):
        self.speed += speed
        if self.speed > self.__max_speed :
            self.speed = 200
    
    def setter(self, max_speed):
        if max_speed > 200:
            print('less than 200')
        else:
            self.__max_speed = max_speed
    
    def getter(self):
        print(self.__max_speed, 'km/h')
    
    def disp(self):
        print(self.speed, self.__max_speed)
        
    max_speed = property(getter, setter)
````

### 6. 모듈(Module)

### 7. 패키지(Package)

### 8. 예외처리(Exception)

### 9. 입출력(IO)

### 10. 정규 표현식(Regex)
- 문자열 데이터를 특정 패턴으로 처리하는 문법
- 함수
    - findall : 일치하는 패턴을 모두 찾기
    - sub : 특정 패턴을 찾아서 문자열을 치환
- 패턴
    - 문자 : `[]`
    - 범위 : `-`
    - 문자 하나 : `.`
    - 0회 1회 반복 : `?`
    - 0회 이상 반복 : `*`
    - 1회 이상 반복 : `+`
    - m회 반복 : `{m}`
    - m~n회 반복 : `{m, n}`
    - 그룹핑 : `()`

In [62]:
# 이메일 찾기
import re
data = "저의 이메일 주소는 abcd1234@gmail.com 과 1234abcd@naver.com을 사용합니다."
pattern = "([a-zA-Z0-9._]+)@([a-z0-9]+)[a-z0-9.]+"
re.findall(pattern, data)

[('abcd1234', 'gmail'), ('1234abcd', 'naver')]

In [69]:
# 주민등록번호 패턴을 찾아서 치환
data = "저의 주민등록번호는 011211-1098765 입니다."
re.findall("[0-9]{6}.?[1-4]{1}[0-9]{6}", data)

['011211-1098765']

In [70]:
re.sub("([0-9]{6}.?[1-4]{1})([0-9]{6})", "\g<1>******" , data)

'저의 주민등록번호는 011211-1****** 입니다.'

In [71]:
# 저의 연락처는 공일0-칠영19오O삼7 입니다. -> 010-7019-5037
datas = '저의 연락처는 공일0-칠영19오O삼7 입니다.'
pattern = '([공영일이삼사오육칠팔구0-9O]{3})(.?)([공영일이삼사오육칠팔구0-9O]{4})(.?)([공영일이삼사오육칠팔구0-9O]{4})'
new_data = re.findall(pattern, datas)
result = "".join(new_data[0])
trans_result = []

num_ls1 = ['영', '일', '이', '삼', '사', '오', '육', '칠', '팔', '구', '공', 'O',
          '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
num_ls2 = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '0',
           '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
num_dic = dict(zip(num_ls1, num_ls2))

for x in range(len(result)):
    for data in num_dic:
        if result[x] == data :
            trans_result.append(num_dic[data])
        
text = "".join(trans_result)
pattern_2 = '([0-9]{3})(.?)([0-9]{4})(.?)([0-9]{4})'
text = re.sub(pattern, '\g<1>-\g<3>-\g<5>', text)

new_data = re.sub(pattern,text ,datas)
print(datas)
print(new_data)

저의 연락처는 공일0-칠영19오O삼7 입니다.
저의 연락처는 010-7019-5037 입니다.


### 11. Numpy
- 데이터는 행렬로 표현
- 행렬 데이터를 빠르게 계산해야함
- 행렬 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지

#### 11-1. 행렬 데이터 생성

In [76]:
# 행렬 데이터 생성
# ndarray 타입 : 한가지 데이터 타입만 값으로 사용이 가능
array = np.array([1,2,3])
type(array),array

(numpy.ndarray, array([1, 2, 3]))

In [82]:
# ndim = 행렬의 차원
# shape = 행렬 모양 : n x m
array2 = np.array([[1,2,3],
                  [4,5,6]])
array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [78]:
# 행렬 모양(shape) 변경
# reshape(*args) - argument의 값들의 곱이 같아야 변경 가능
array2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [79]:
array2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [80]:
# 행렬 데이터의 선택 : offset index
# masking
array2[1][::-1]

array([6, 5, 4])

In [81]:
array2[1,2] # array2[1][2]

6

In [83]:
# 데이터 수정
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

#### 11-2. 브로드캐스팅

In [84]:
# 브로드 캐스팅
array2[0] = [7, 8, 9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [87]:
# 조건으로 선택
idx = array2 > 7
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

#### 11-3. linspace, logspace
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logsapce : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [89]:
np.linspace(0,100,5), np.logspace(2, 4, 3)

(array([  0.,  25.,  50.,  75., 100.]), array([  100.,  1000., 10000.]))

#### 11-4. numpy random
- seed : 랜덤값을 설정값
- rand : 균등분포로 난수 발생
- randn : 정규분포로 난수 발생
- randint : 균등분포로 정수값 발생
- suffle : 행렬 데이터를 섞어줌
- choice : 특정 확률로 데이터를 선택

In [90]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [91]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [95]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[7, 7, 4, 9],
       [3, 2, 5, 9],
       [2, 7, 6, 2]])

In [97]:
np.random.shuffle(r)
r

array([[3, 2, 5, 9],
       [7, 7, 4, 9],
       [2, 7, 6, 2]])

In [98]:
# 가장 바깥쪽 차원의 값만 바뀜 (행 단위로 섞임)
# 모두 바꾸고 싶은 경우
# reshape사용 -> 1차원으로 변환 suffle -> 기존 차원으로 다시 reshape
r2 = r.reshape(12)
np.random.shuffle(r2)
r2.reshape(3, 4)

array([[7, 9, 2, 6],
       [3, 2, 9, 5],
       [2, 7, 7, 4]])

In [99]:
# choice
np.random.choice(5, 10, p =[0.1, 0.4, 0.3, 0.2, 0])

array([1, 2, 3, 2, 2, 3, 2, 2, 1, 3])

In [101]:
# unique
numbers, counts = np.unique(r, return_counts = True)
print(numbers)
print(counts)


[2 3 4 5 6 7 9]
[3 1 1 1 1 3 2]


#### 11-5. 행렬 데이터의 결합
- concatenate

In [102]:
na1 = np.random.randint(10, size = (2,3))
na2 = np.random.randint(10, size = (3,2))
na3 = np.random.randint(10, size = (3,3))

In [103]:
# 세로 결합
np.concatenate((na1,na3))

array([[3, 6, 1],
       [4, 0, 8],
       [9, 2, 1],
       [0, 7, 1],
       [8, 9, 0]])

In [104]:
# 가로 결합
# 함수의 axis 값을 항상 확인하고 사용 
# axis = 축, axis = 0 -> 세로, axis = 1 -> 가로
np.concatenate((na2, na3), axis =1)

array([[5, 4, 9, 2, 1],
       [2, 9, 0, 7, 1],
       [7, 1, 8, 9, 0]])

In [105]:
# c_, r_
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [106]:
np.r_['1, 2, 0', np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 12. Pandas
- 데이터 타입
    - Series : index와 value로 이루어진 데이터 타입
    - DataFrame : index, column, value로 이루어진 데이터 타입
        - column은 index와 value 모두 포함 -> column 한줄이 하나의 Series

#### 12-1. Series
- Series는 동일한 데이터 타입을 가짐(ndarray와 동일)

In [107]:
# Serise : value만 설정하면 index는 0부터 자동으로 설정
data = pd.Series(np.random.randint(10, size=5))
data

0    7
1    0
2    5
3    2
4    5
dtype: int32

In [108]:
# index 설정
data.index= list("ABCDE")
data

A    7
B    0
C    5
D    2
E    5
dtype: int32

In [109]:
# data.index : Series의 인덱스 모두 호출
# data.values : Series의 value값 모두 호출
data.index, data.values

(Index(['A', 'B', 'C', 'D', 'E'], dtype='object'), array([7, 0, 5, 2, 5]))

In [110]:
# index가 value값의 key값임
# 특정 인덱스의 데이터 호출 및 변환
data['C'] = 10
data['C']

10

In [111]:
# 브로드캐스팅 및 오프셋 인덱스 모두 list와 유사
data * 10

A     70
B      0
C    100
D     20
E     50
dtype: int32

#### 12-2. Series 연산
- 같은 index끼리만 연산되며 둘중 하나라도 값이 없을 경우 NaN 반환
- .isnull() : value 값이 null인 경우 True

In [112]:
data2 = pd.Series({"D":3, "E":5, "F":7})
data2

D    3
E    5
F    7
dtype: int64

In [113]:
result = data + data2
result

A     NaN
B     NaN
C     NaN
D     5.0
E    10.0
F     NaN
dtype: float64

In [114]:
result.isnull()

A     True
B     True
C     True
D    False
E    False
F     True
dtype: bool

In [119]:
# value 값이 true인 것만 result에서 출력
# 마스킹
result[result.isnull()] = data
result[result.isnull()] = data2
result

A     7.0
B     0.0
C    10.0
D     5.0
E    10.0
F     7.0
dtype: float64

#### 12-3. DataFrame
- 데이터 프레임 생성 1: 딕셔너리의 리스트
````
datas = {
    "name":['dss', 'fastcamp'],
    "email":['dss@gmail.com', 'fastcamp.net'],
}
````
- 데이터 프레임 생성 2: 리스트의 딕셔너리
````
datas = [
    {'name':'dss','email':'dss@gmail.com'},
    {'name':'fcamp','email':'fcamp@facamp.net'}
]
````
- .columns : 데이터 프레임의 column이름 리스트
- .values : 데이터 프레임의 데이터 리스트
- .head : 상위 N개의 데이터 출력 default = 5
- .tail : 하위 N개의 데이터 출력 default = 5

In [126]:
datas = {
  "name":['dss', 'fastcamp'],
  "email":['dss@gmail.com', 'fastcamp.net'],
}
df = pd.DataFrame(datas)
df

name          email
0       dss  dss@gmail.com
1  fastcamp   fastcamp.net

In [127]:
# 인덱스 추가
datas = pd.DataFrame(datas, index = range(1,3))
datas

name          email
1       dss  dss@gmail.com
2  fastcamp   fastcamp.net

In [130]:
df.columns

Index(['name', 'email'], dtype='object')

In [135]:
# 데이터 프레임에서 데이터의 선택 : row, column, (row, column)
# 2행의 email 컬럼의 데이터 출력
# index가 있으면 수정, 없으면 추가
# column이 없으면 새로운 column 추가
df.loc[1]['email']

'fastcamp.net'

#### 12-4. apply
- map 함수와 유사
````
    def domain(email):
        # split[0] 스플릿 기준 앞의 문자열, [1] 뒤의 문자열
        return email.split("@")[1].split(".")[0]      

    df["domain"] = df["email"].apply(domain)
````


#### 12-5. append
- 데이터프레임 합치기
- df.append(df, ignore_index = True) -> ignore_index = True : 자동 인덱스 정렬
````
    df3 = df1.append(df2)
````
- reset_index()만 실행했을 경우 재정렬된 객체값만 존재
- drop = True -> 기존의 index를 제외하고 결과만 출력해줌
- inplace = True 객체에 바뀐 내용을 저장하고 출력
````
    df3.reset_index(drop=True, inplace=True)
````

#### 12-6. concat
- row나 column으로 데이터 프레임을 합칠때 사용